### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dr5hn** [thiagobueno/countries-states-cities#1]
Hi @thiagobueno,

This is Darshan Gada here, the owner of Repo: https://github.com/dr5hn/countries-states-cities-database.

Firstly, I would like to thank you for building this wonderful package and making the database to reach more people.

FYI,
Recently I have made a few improvements to my Database. Hope you would like to integrate it into this package as well.

In countries, I have added
- Timezones
- Latitude
- Longitude

In states, I have added
- Latitude
- Longitude

**Comment by thiagobueno** [comment]
Hi @dr5hn 

Thank you for your work, congratulations.

I will update today with your new content, thank you very much.
